issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude:
      - SA1019

run:
  deadline: 5m
  skip-files:
      - avi/resource_avi_rest_dependants.go

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosimple
    - ineffassign
    - interfacer
    - nakedret
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - varcheck
    - vet
    - vetshadow

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
